// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Run_Partner.Data;

#nullable disable

namespace Run_Partner.Migrations
{
    [DbContext(typeof(RunPartnerDbContext))]
    [Migration("20240814164124_photos added")]
    partial class photosadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Run_Partner.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnownAs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("datetime2");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            City = "Yonah",
                            Country = "New Zealand",
                            Created = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1967, 12, 14),
                            Gender = "female",
                            Introduction = "Eu amet velit nostrud eu irure. Dolor pariatur commodo excepteur occaecat ad. Commodo mollit nulla ullamco sint qui laborum commodo veniam. Ut adipisicing excepteur duis laboris Lorem proident.\r\n",
                            KnownAs = "Rosetta",
                            LastActive = new DateTime(2024, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "In velit aliqua aute sint duis deserunt dolore nostrud consequat aute fugiat non. Nisi adipisicing magna qui est adipisicing elit quis sunt labore ut. Dolore ullamco nisi enim proident dolor eu. Exercitation enim deserunt esse do nostrud ex officia nisi et pariatur excepteur anim sit. Laboris sunt aliquip sunt sit sint sunt amet voluptate occaecat. Fugiat pariatur nisi deserunt aliquip exercitation culpa ullamco excepteur.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Rosetta"
                        },
                        new
                        {
                            Id = -2,
                            City = "Olney",
                            Country = "Denmark",
                            Created = new DateTime(2019, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1956, 2, 2),
                            Gender = "female",
                            Introduction = "Enim veniam magna sunt dolore commodo. Lorem laboris sit laboris incididunt proident laboris incididunt deserunt elit pariatur cupidatat cupidatat minim ullamco. Velit aliqua laborum nulla reprehenderit irure nisi nisi incididunt in non elit irure.\r\n",
                            KnownAs = "Sasha",
                            LastActive = new DateTime(2022, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Laboris aliquip exercitation pariatur laborum veniam cillum est eiusmod. Elit enim aliquip ex qui mollit et Lorem voluptate reprehenderit dolore Lorem Lorem cillum quis. Quis eiusmod ea duis minim non voluptate quis Lorem. Velit nulla quis ullamco incididunt non ad ea do ad incididunt mollit ut ad magna. Dolor cupidatat ad exercitation consequat exercitation aute et adipisicing amet ipsum dolore consequat esse. Minim do laborum ullamco consequat proident aliqua incididunt nulla.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Sasha"
                        },
                        new
                        {
                            Id = -3,
                            City = "Rutherford",
                            Country = "Mauritania",
                            Created = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1961, 7, 13),
                            Gender = "female",
                            Introduction = "Non quis anim eiusmod excepteur cupidatat exercitation aute. Id tempor minim non commodo. Aliquip ipsum Lorem id deserunt aliqua reprehenderit nisi ad. Tempor laboris incididunt aute labore amet velit sit. Tempor consectetur nostrud nisi ad aute commodo. Velit aliquip ipsum est pariatur et in cupidatat ad et labore tempor cupidatat proident aute. Non sit enim ut labore qui eiusmod labore enim fugiat aliquip laborum.\r\n",
                            KnownAs = "Cherie",
                            LastActive = new DateTime(2023, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Eu sint enim laborum nisi nostrud do cillum adipisicing enim voluptate sunt velit. Excepteur amet ut aliqua excepteur dolor non ipsum aute anim ex proident consequat aliquip. Ex anim excepteur minim veniam eiusmod adipisicing. Exercitation magna aliquip excepteur esse et deserunt fugiat labore. Nostrud ex magna cupidatat magna ullamco dolore veniam anim. Cupidatat pariatur adipisicing veniam proident duis.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Cherie"
                        },
                        new
                        {
                            Id = -4,
                            City = "Jenkinsville",
                            Country = "Latvia",
                            Created = new DateTime(2020, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1983, 11, 24),
                            Gender = "female",
                            Introduction = "Amet nisi ipsum aliquip reprehenderit excepteur eu ea et quis tempor. Proident officia pariatur mollit cupidatat nulla deserunt adipisicing ut velit. Labore eiusmod consequat esse ipsum elit est proident occaecat Lorem ut amet officia. Dolore adipisicing labore eu cillum id id consectetur enim consequat velit labore mollit proident.\r\n",
                            KnownAs = "Josie",
                            LastActive = new DateTime(2021, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Anim id eiusmod exercitation aliqua non reprehenderit culpa ea veniam aliquip culpa officia adipisicing. Sunt in velit fugiat laboris pariatur dolore officia proident et cillum excepteur. Occaecat nostrud id sit enim esse proident fugiat ipsum elit eu exercitation mollit mollit nulla. Aute irure consectetur do reprehenderit id. Cillum mollit ex tempor ea minim cupidatat aute fugiat Lorem id reprehenderit ut laborum deserunt. Adipisicing consectetur labore ad officia nisi consectetur.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Josie"
                        },
                        new
                        {
                            Id = -5,
                            City = "Veyo",
                            Country = "South Africa",
                            Created = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1959, 6, 3),
                            Gender = "female",
                            Introduction = "Sunt ipsum non laborum ea eu excepteur nulla. Excepteur Lorem sint dolor ut sint ipsum incididunt id dolore. Consectetur aute sit in ut nisi sint consectetur.\r\n",
                            KnownAs = "Eugenia",
                            LastActive = new DateTime(2021, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Sit Lorem non adipisicing aute reprehenderit. Aute sunt consequat officia ullamco cupidatat ex laborum sunt exercitation qui nulla tempor mollit. Exercitation Lorem adipisicing sit occaecat cillum irure. Sint esse ea ex quis eu. Officia eu et ea minim reprehenderit excepteur pariatur aliquip culpa ullamco aute. Anim incididunt exercitation magna enim aute Lorem id culpa consequat adipisicing commodo ullamco. Elit culpa elit esse enim et.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Eugenia"
                        },
                        new
                        {
                            Id = -6,
                            City = "Defiance",
                            Country = "Senegal",
                            Created = new DateTime(2019, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1985, 2, 25),
                            Gender = "male",
                            Introduction = "Laboris consequat ut eu mollit dolore sint aliquip. Pariatur ea minim et anim mollit sint sunt ullamco velit officia. Excepteur excepteur aliqua aliquip proident anim ipsum cupidatat eu non culpa sint dolor anim veniam. Cupidatat id nostrud voluptate excepteur. Reprehenderit Lorem excepteur quis qui sunt.\r\n",
                            KnownAs = "Crawford",
                            LastActive = new DateTime(2023, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Officia ullamco tempor magna eu do cupidatat cillum do. Nisi irure ea aliqua dolor culpa ea cillum Lorem enim. Cillum tempor eu cupidatat qui aute tempor excepteur incididunt eu tempor. Id elit laboris duis ex esse magna qui. Anim Lorem adipisicing dolor anim occaecat aute veniam sint excepteur. Laborum ut sunt ut magna ad consequat enim. Sint cupidatat qui excepteur mollit proident irure veniam in duis excepteur consequat.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Crawford"
                        },
                        new
                        {
                            Id = -7,
                            City = "Shady Grove",
                            Country = "Greece",
                            Created = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1952, 1, 29),
                            Gender = "male",
                            Introduction = "Dolore dolor anim velit esse consequat id aute voluptate. Adipisicing aliqua ea sunt consectetur et aliqua excepteur. In nulla dolore exercitation ea aliqua fugiat irure in eiusmod exercitation aute occaecat esse. Sint dolore nostrud adipisicing nostrud consequat duis veniam nisi qui nulla.\r\n",
                            KnownAs = "Leblanc",
                            LastActive = new DateTime(2022, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Aute ipsum ex nostrud dolore ad sint. Lorem id nisi irure laboris aliqua officia pariatur cupidatat exercitation irure. Enim in dolore nostrud nisi occaecat dolor exercitation culpa dolore. Magna tempor laborum sunt velit fugiat qui. Duis proident velit deserunt eiusmod mollit aliqua nostrud duis.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Leblanc"
                        },
                        new
                        {
                            Id = -8,
                            City = "Hickory",
                            Country = "Lithuania",
                            Created = new DateTime(2020, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1994, 4, 27),
                            Gender = "male",
                            Introduction = "Non mollit in ad aute eiusmod nulla aute tempor proident. Reprehenderit occaecat laboris ipsum esse reprehenderit sunt irure tempor in irure dolore cillum. Mollit ullamco voluptate magna laborum do do veniam dolor aliqua culpa ea reprehenderit voluptate ut.\r\n",
                            KnownAs = "Scott",
                            LastActive = new DateTime(2021, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LookingFor = "Sunt tempor voluptate id nulla dolore aliquip enim enim occaecat occaecat Lorem ex dolore. Aliqua excepteur Lorem ut laborum proident pariatur incididunt nulla. Non veniam ad adipisicing sunt dolor labore dolore. Cillum sunt culpa duis nulla tempor. Amet mollit ea ex magna. Officia non tempor magna aute irure anim adipisicing. Amet culpa nostrud voluptate laborum.\r\n",
                            PasswordHash = new byte[] { 56, 198, 119, 175, 165, 243, 108, 38, 152, 192, 32, 107, 100, 39, 110, 141, 5, 136, 24, 176, 117, 87, 136, 57, 238, 9, 170, 85, 168, 115, 110, 191, 177, 251, 193, 220, 140, 224, 159, 30, 49, 134, 75, 237, 234, 89, 122, 170, 153, 26, 82, 123, 87, 33, 247, 147, 112, 79, 0, 124, 125, 125, 144, 147 },
                            PasswordSalt = new byte[] { 53, 135, 166, 130, 107, 233, 222, 115, 63, 103, 195, 238, 23, 48, 108, 185, 234, 189, 49, 107, 56, 95, 25, 63, 162, 35, 10, 146, 185, 192, 247, 228, 140, 153, 78, 81, 72, 47, 124, 137, 11, 9, 121, 89, 87, 105, 108, 46, 28, 125, 74, 225, 9, 213, 7, 156, 53, 125, 118, 182, 119, 233, 27, 95, 118, 118, 243, 140, 229, 118, 37, 47, 155, 100, 179, 213, 33, 33, 180, 125, 244, 213, 52, 10, 76, 31, 80, 202, 96, 70, 51, 160, 148, 110, 67, 237, 13, 50, 41, 44, 8, 117, 135, 199, 170, 199, 147, 149, 94, 46, 77, 223, 170, 163, 144, 99, 26, 186, 50, 93, 151, 216, 246, 140, 176, 215, 226, 64 },
                            UserName = "Scott"
                        });
                });

            modelBuilder.Entity("Run_Partner.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AppUserId = -1,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/women/10.jpg"
                        },
                        new
                        {
                            Id = -2,
                            AppUserId = -2,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/women/20.jpg"
                        },
                        new
                        {
                            Id = -3,
                            AppUserId = -3,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/women/30.jpg"
                        },
                        new
                        {
                            Id = -4,
                            AppUserId = -4,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/women/40.jpg"
                        },
                        new
                        {
                            Id = -5,
                            AppUserId = -5,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/women/50.jpg"
                        },
                        new
                        {
                            Id = -6,
                            AppUserId = -6,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/men/10.jpg"
                        },
                        new
                        {
                            Id = -7,
                            AppUserId = -7,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/men/20.jpg"
                        },
                        new
                        {
                            Id = -8,
                            AppUserId = -8,
                            IsMain = true,
                            Url = "https://randomuser.me/api/portraits/men/30.jpg"
                        });
                });

            modelBuilder.Entity("Run_Partner.Models.Photo", b =>
                {
                    b.HasOne("Run_Partner.Models.AppUser", "AppUser")
                        .WithMany("Photos")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Run_Partner.Models.AppUser", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
