// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Run_Partner.Data;

#nullable disable

namespace Run_Partner.Migrations
{
    [DbContext(typeof(RunPartnerDbContext))]
    partial class RunPartnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Run_Partner.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d655afc-1939-429f-ac99-cfb3140218f9"),
                            UserName = "Ahmed"
                        },
                        new
                        {
                            Id = new Guid("f0c07f18-a85b-4b16-860e-5ed4bcee4c83"),
                            UserName = "Abbas"
                        },
                        new
                        {
                            Id = new Guid("dad4aee9-fa78-44eb-ba21-beb10274972f"),
                            UserName = "Joha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
